name: mi_service
description: Monitoreo de Flotas App

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  riverpod: ^2.4.0
  dio: ^5.3.2
  shared_preferences: ^2.2.1
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  intl: ^0.18.1
  flutter_map: ^6.1.2
  equatable: ^2.0.5
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true