export enum TipoAlerta {
    EMERGENCIA = "EMERGENCIA",
    EXCESO_VELOCIDAD = "EXCESO_VELOCIDAD",
    FALLA_MECANICA = "FALLA_MECANICA",
    COMBUSTIBLE_BAJO = "COMBUSTIBLE_BAJO",
    PERDIDA_GPS = "PERDIDA_GPS"
}
